{% set name = "vbz-h5py-plugin" %}
{% set version = "1.0.13" %}

package:
  name: {{name}}
  version: '{{version}}'

source:
  git_url: https://github.com/nanoporetech/vbz_compression.git
  git_rev: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("vbz-h5py-plugin", max_pin="x") }}

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
    - osx-64
  skip-lints:
    # This needs git for recursive checkouts
    - uses_vcs_url
    - missing_hash

  
requirements:
  build:
    - make
    - '{{ compiler("c") }}'
    - '{{ compiler("cxx") }}'
    - cmake
    - git-lfs
  host:
    - hdf5
    - zstd
  run:
    - zstd
    - hdf5  

test:
  source_files:
    - test_data/multi_fast5_vbz_v1.fast5

about:
  home: https://github.com/nanoporetech/vbz_compression.git
  license: MPL-2
  license_file: LICENCE.txt
  license_family: MOZILLA
  summary: VBZ compression plugin for nanopore signal data