{% set version = "1.0.1" %}
{% set name = "vbz-h5py-plugin" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  number: 0
  script:
    - export LD_LIBRARY_PATH=${PREFIX}/lib:${LD_LIBRARY_PATH}
    - $PYTHON -m pip install --prefix=${PREFIX} https://pypi.io/packages/py3/{{ name[0] }}/{{ name}}/vbz_h5py_plugin-{{ version }}-py3-none-any.whl

requirements:
  host:
    - python
    - pip
    - h5py
  run:
    - python
    - h5py

test:
  imports:
    - vbz_h5py_plugin
  commands:
    - python -c "import vbz_h5py_plugin"

about:
  home: https://github.com/nanoporetech/vbz-h5py-plugin
  license: Mozilla Public License Version 2.0
  summary: 'This module provides a plugin to H5Py for the VBZ (de)compression library.'
  description: |
    VBZ compression is a compression algorithm developed by Oxford Nanopore to reduce file size and improve read/write performance when handling raw data in POD5/Fast5 files. Previously, the default compression was GZIP and comparing to GZIP we see a compression improvement of >30% and a CPU performance improvement of >10X for compression and >5X for decompression. Further details of the implementation and benchmarks can be found here: ![Nanoporetech/vbz_compression](https://github.com/nanoporetech/vbz_compression)